In [1]:
pip show numpy


Name: numpy
Version: 2.4.2
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License-Expression: BSD-3-Clause AND 0BSD AND MIT AND Zlib AND CC0-1.0
Location: C:\Users\Nirav\Desktop\project\venv\Lib\site-packages
Requires: 
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np


In [2]:
arr= np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
a = [1,3.5]
a


[1, 3.5]

In [4]:
l = np.array(a)
l

array([1. , 3.5])

In [5]:
list = [[1,2,3],[4,5,6],[7,8,9]]
list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.array([[1,2],[3,4]])


array([[1, 2],
       [3, 4]])

### Array generation function

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

### Random Generation functions

In [13]:
np.random.rand(10)

array([0.47414119, 0.64618625, 0.24481266, 0.97576731, 0.2712935 ,
       0.69684878, 0.57084373, 0.12090529, 0.4818186 , 0.53575085])

In [14]:
np.random.randn(6)

array([ 0.33323657, -0.98620825,  1.41502705,  0.69295289,  1.27361681,
       -0.1883874 ])

In [17]:
np.random.randint(7)

6

In [18]:
np.random.randint(10,20,10)

array([10, 11, 14, 13, 18, 15, 11, 16, 19, 10], dtype=int32)

### Array attributes

In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr.shape

(3, 3)

In [21]:
arr.size

9

In [22]:
arr.dtype

dtype('int64')

### Array method

In [23]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr.min()


np.int64(1)

In [26]:
arr.max()

np.int64(9)

In [27]:
arr.sum()

np.int64(45)

In [30]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [31]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [32]:
arr.mean()

np.float64(5.0)

### Resizing and Reshaping

In [33]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [35]:
arr= arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])