In [1]:
import numpy as np


### for array

In [3]:
arr =np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[1:5]

array([12, 13, 14, 15])

In [7]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [11]:
arr[3::2]

array([14, 16, 18, 20])

In [12]:
arr[4]

np.int64(15)

### NUMPY INDEXING AND SLICING

In [16]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [17]:
arr[0]

array([1, 2, 3, 4, 5])

In [18]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [20]:
arr[0,0]

np.int64(1)

In [21]:
arr[0,1]

np.int64(2)

In [22]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [24]:
arr[5,4]

np.int64(30)

In [26]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [28]:
slice = arr[2:4,0:2]
slice

array([[11, 12],
       [16, 17]])

In [30]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [31]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [32]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [33]:
arr[:,1]

array([ 2,  7, 12, 17, 22, 27])

In [34]:
arr[:,4]

array([ 5, 10, 15, 20, 25, 30])

### BOOLEAN INDEXING

In [36]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])